name: Sync GitLab mirror

on:
  push:
    branches: [ "main" , "dev" ]

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Mirror to GitLab
        env:
          GITLAB_URL: https://gitlab.com/iahmadgad/termux-clock.git
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          BRANCH: ${{ github.ref_name }}
        run: |
          git remote add gitlab "$GITLAB_URL"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git push https://oauth2:$GITLAB_TOKEN@$GITLAB_URL $BRANCH --force
