name: Rust CI

on:
  push:
    branches: [ "main" , "dev" ]
    paths-ignore:
      - "*.md"
      - "LICENSE"
  pull_request:
    branches: [ "main", "dev" ]
    paths-ignore:
      - "*.md"
      - "LICENSE"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
   
    name: Build and test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies and binaries
        uses: Swatinem/rust-cache@v2

      - name: Build
        shell: bash
        run: cargo build --verbose
     
      - name: Test
        shell: bash
        run: cargo test --verbose
