name: Rust CI

on:
  push:
    branches: [ "main" , "dev" ]
    paths-ignore:
      - "*.md"
      - "LICENSE"
  pull_request:
    branches: [ "main", "dev" ]
    paths-ignore:
      - "*.md"
      - "LICENSE"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
   
    name: Build and test
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies and binaries
        uses: Swatinem/rust-cache@v2

      - name: Install development tools
        uses: taiki-e/install-action@v2.68.21
        with:
          tool: just

      - name: Install cross
        shell: bash
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Build for aarch64-linux-android
        shell: bash
        run: just cross-build aarch64

      - name: Build for arm-linux-androideabi
        shell: bash
        run: just cross-build arm

      - name: Build for x86_64-linux-android
        shell: bash
        run: just cross-build x86_64
            
      - name: Build for i686-linux-android
        shell: bash
        run: just cross-build i686
     
      - name: Test
        shell: bash
        run: cargo test --verbose
