name: Sync

on:
  push:
    branches: [ "main" ]
    tags: [ "*.v" ]

jobs:
  dev-branch:
    name: Sync dev branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          ref: dev
          fetch-depth: 0  # Fetch full history, including tags

      - name: Sync dev with main
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git merge origin/main
          git push -u origin dev
        
  gitlab-mirror:
    name: Sync GitLab Mirror
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch full history, including tags
        
      - name: Push to GitLab mirror
        env:
          GITLAB_URL: gitlab.com/iahmadgad/termux-clock.git
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab "$GITLAB_URL"
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          # Push main branch
          git push https://oauth2:$GITLAB_TOKEN@$GITLAB_URL main --force

          # Push tags associated with these branches
          git push https://oauth2:$GITLAB_TOKEN@$GITLAB_URL --tags
